Document: composer-aliases
Title: Debian composer-aliases Manual
Author: <insert document author here>
Abstract: This manual describes what composer-aliases is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/composer-aliases/composer-aliases.sgml.gz

Format: postscript
Files: /usr/share/doc/composer-aliases/composer-aliases.ps.gz

Format: text
Files: /usr/share/doc/composer-aliases/composer-aliases.text.gz

Format: HTML
Index: /usr/share/doc/composer-aliases/html/index.html
Files: /usr/share/doc/composer-aliases/html/*.html
